// -*- C++ -*-
//
// generated by wxGlade not found on Tue Jun  5 23:21:40 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DFARCFRAME_BASE_H
#define DFARCFRAME_BASE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/splitter.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DFArcFrame_Base: public wxFrame {
public:
    // begin wxGlade: DFArcFrame_Base::ids
    enum {
        ID_FileInstall = wxID_HIGHEST + 1009,
        ID_Download = wxID_HIGHEST + 1010,
        ID_Refresh = wxID_HIGHEST + 1011,
        ID_Browse = wxID_HIGHEST + 1012,
        ID_Uninstall = wxID_HIGHEST + 1013,
        ID_Options = wxID_HIGHEST + 1014,
        ID_IntroductionText = wxID_HIGHEST + 1015,
        ID_Walkthroughs = wxID_HIGHEST + 1016,
        ID_Forums = wxID_HIGHEST + 1017,
        ID_DmodTitleList = wxID_HIGHEST + 1028,
        ID_Play = wxID_HIGHEST + 1030,
        ID_Truecolor = wxID_HIGHEST + 1032,
        ID_Windowed = wxID_HIGHEST + 1034,
        ID_Sound = wxID_HIGHEST + 1036,
        ID_Joystick = wxID_HIGHEST + 1038,
        ID_Debug = wxID_HIGHEST + 1040,
        ID_V107 = wxID_HIGHEST + 1042,
        ID_Edit = wxID_HIGHEST + 1044,
        ID_Package = wxID_HIGHEST + 1046,
    };
    // end wxGlade

    DFArcFrame_Base(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: DFArcFrame_Base::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DFArcFrame_Base::attributes
    wxMenuBar* lMenuBar;
    wxStatusBar* mStatusBar;
    wxListBox* mDModListBox;
    wxButton* mPlayButton;
    wxCheckBox* mTrueColor;
    wxCheckBox* mWindowed;
    wxCheckBox* mSound;
    wxCheckBox* mJoystick;
    wxCheckBox* mDebug;
    wxCheckBox* mV107;
    wxButton* mEditButton;
    wxButton* mPackageButton;
    wxPanel* mAnimationPanel;
    wxChoice* mGameLocaleList;
    wxPanel* panel_1;
    wxTextCtrl* mDmodDescription;
    wxSplitterWindow* mSplitter;
    // end wxGlade
}; // wxGlade: end class


#endif // DFARCFRAME_BASE_H
