// -*- C++ -*-
//
// generated by wxGlade not found on Tue Jun  5 23:21:41 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "InstallVerifyFrame_Base.h"

// begin wxGlade: ::extracode
// end wxGlade



InstallVerifyFrame_Base::InstallVerifyFrame_Base(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
{
    // begin wxGlade: InstallVerifyFrame_Base::InstallVerifyFrame_Base
    mDmodDescription = new wxTextCtrl(this, wxID_ANY, _("Preparing..."), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    const wxString mDestdirBox_choices[] = {
        _("Main Dink directory"),
        _("Additional D-Mods directory"),
    };
    mDestdirBox = new wxRadioBox(this, wxID_ANY, _("Where do you want to install this D-Mod?"), wxDefaultPosition, wxDefaultSize, 2, mDestdirBox_choices, 0, wxRA_SPECIFY_ROWS);
    mInstallButton = new wxButton(this, wxID_OK, _("Install"));
    mCancelButton = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void InstallVerifyFrame_Base::set_properties()
{
    // begin wxGlade: InstallVerifyFrame_Base::set_properties
    SetTitle(_("DFArc - Install D-Mod"));
    mDmodDescription->SetMinSize(wxSize(390,150));
    mDestdirBox->SetSelection(0);
    mInstallButton->SetFocus();
    mInstallButton->SetDefault();
    // end wxGlade
}


void InstallVerifyFrame_Base::do_layout()
{
    // begin wxGlade: InstallVerifyFrame_Base::do_layout
    wxBoxSizer* lVerticalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* lHorizontalSizer = new wxBoxSizer(wxHORIZONTAL);
    lVerticalSizer->Add(mDmodDescription, 1, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 5);
    lVerticalSizer->Add(mDestdirBox, 0, wxEXPAND, 0);
    lHorizontalSizer->Add(mInstallButton, 0, 0, 0);
    lHorizontalSizer->Add(mCancelButton, 0, wxLEFT, 5);
    lVerticalSizer->Add(lHorizontalSizer, 0, wxALL|wxEXPAND, 5);
    SetSizer(lVerticalSizer);
    lVerticalSizer->Fit(this);
    Layout();
    // end wxGlade
}

