// -*- C++ -*-
//
// generated by wxGlade not found on Tue Jun  5 23:21:40 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef OPTIONS_BASE_H
#define OPTIONS_BASE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class Options_Base: public wxDialog {
public:
    // begin wxGlade: Options_Base::ids
    enum {
        ID_OVERRIDE_DINKREFDIR_BROWSE = wxID_HIGHEST + 1001,
        ID_DMODDIR_BROWSE = wxID_HIGHEST + 1003,
        ID_LANGUAGE_LIST = wxID_HIGHEST + 1005,
    };
    // end wxGlade

    Options_Base(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: Options_Base::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: Options_Base::attributes
    wxCheckBox* mCloseCheck;
    wxCheckBox* mShowDeveloperCheck;
    wxCheckBox* mWriteIniCheck;
    wxCheckBox* mOverrideDinkrefDirCheck;
    wxTextCtrl* mOverrideDinkrefDirBox;
    wxButton* mOverrideDinkrefDirBrowse;
    wxStaticText* lDModDirLabel;
    wxTextCtrl* mDModDirBox;
    wxButton* mDModDirBrowse;
    wxStaticText* lDinkExeLabel;
    wxComboBox* mDinkExeBox;
    wxStaticText* lEditorExeLabel;
    wxComboBox* mEditorExeBox;
    wxStaticText* mPreferredFileBrowserLabel;
    wxTextCtrl* mPreferredFileBrowserBox;
    wxStaticText* lForceLocaleLabel;
    wxChoice* mLanguageList;
    wxTextCtrl* mForceLocaleBox;
    wxButton* lOkay;
    wxButton* lCancel;
    // end wxGlade
}; // wxGlade: end class


#endif // OPTIONS_BASE_H
