// -*- C++ -*-
//
// generated by wxGlade not found on Tue Jun  5 23:21:41 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PACKAGE_BASE_H
#define PACKAGE_BASE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class Package_Base: public wxDialog {
public:
    // begin wxGlade: Package_Base::ids
    // end wxGlade

    Package_Base(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: Package_Base::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: Package_Base::attributes
    wxStaticText* lIntroText;
    wxStaticText* lIdentifierText;
    wxTextCtrl* mIdentifier;
    wxButton* mOkay;
    wxButton* mCancel;
    // end wxGlade
}; // wxGlade: end class


#endif // PACKAGE_BASE_H
