// -*- C++ -*-
//
// generated by wxGlade not found on Tue Jun  5 23:21:41 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "Package_Base.h"

// begin wxGlade: ::extracode
// end wxGlade



Package_Base::Package_Base(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
{
    // begin wxGlade: Package_Base::Package_Base
    lIntroText = new wxStaticText(this, wxID_ANY, _("Note: Unless you're making a D-Mod, you shouldn't be around here.\nThis is for creating a .dmod file for a D-Mod you made.\n\nWill package '%s' located at\n%s"));
    lIdentifierText = new wxStaticText(this, wxID_ANY, _("D-Mod filename (8 letters/numbers)"));
    mIdentifier = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    mOkay = new wxButton(this, wxID_OK, _("Package"));
    mCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void Package_Base::set_properties()
{
    // begin wxGlade: Package_Base::set_properties
    SetTitle(_("DFArc - Package"));
    mOkay->SetDefault();
    // end wxGlade
}


void Package_Base::do_layout()
{
    // begin wxGlade: Package_Base::do_layout
    wxBoxSizer* lMainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* lActionBox = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* lIdentifierBox = new wxStaticBoxSizer(new wxStaticBox(this, wxID_ANY, _("Identifier")), wxHORIZONTAL);
    lMainSizer->Add(lIntroText, 1, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 10);
    lIdentifierBox->Add(lIdentifierText, 1, wxALL|wxEXPAND, 2);
    lIdentifierBox->Add(mIdentifier, 1, wxALIGN_RIGHT|wxALL, 2);
    lMainSizer->Add(lIdentifierBox, 1, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 10);
    lActionBox->Add(mOkay, 0, 0, 0);
    lActionBox->Add(mCancel, 0, wxLEFT, 10);
    lMainSizer->Add(lActionBox, 0, wxALL|wxEXPAND, 10);
    SetSizer(lMainSizer);
    lMainSizer->Fit(this);
    Layout();
    // end wxGlade
}

